/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banco;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicky
 */
public class AppFrame extends javax.swing.JFrame 
{
    private static ModFrame appMod;
    private static AppFrame appPrincipal;
    //Formato: nombre, paterno, nacimiento, procedencia, fondos
    static String[] datos_user = new String[5];
    private static String username;

    /**
     * Creates new form AppFrame
     * @param username
     */
    public AppFrame(String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.username = username;
        this.getData();
        this.jLabel1.setText("Bienvenido "+datos_user[0]);
        this.labelNombre.setText("Nombre: "+datos_user[0]);
        this.labelApellido.setText("Apellido: "+datos_user[1]);
        this.labelFecha.setText("Fecha de Nacimiento: "+datos_user[2]);
        this.labelEdo.setText("Estado de Origen: "+datos_user[3]);
        this.labelFondos.setText("Fondos: "+datos_user[4]);
    }
    /**
     * Metodo que se encarga de obtener la informacion de username_data.txt
     * donde username es una variable.
     */
    public static void getData()
    {
        try {
            File user_data = new File(username+"_data.txt");
            FileReader fr = new FileReader(user_data);
            BufferedReader br = new BufferedReader(fr);
            String cadena_leida;

            while( (cadena_leida = br.readLine() ) != null)
            {
                datos_user = cadena_leida.split(",");
            }
            br.close();
            fr.close();
            
        }catch(IOException e)
        {
            System.out.println("Excepcion de lectura/escritura detectada.");
        }
        
        for(int i = 0; i<datos_user.length; i++)
        {
            System.out.println("["+(i+1)+"]"+datos_user[i]);
        }
    }
    
    /**
     * Metodo que se encarga de escribir la informacion modificada
     */
    public static void writeData()
    {
        try {
            File user_data = new File(username+"_data.txt");
            FileWriter fw = new FileWriter(user_data);
            BufferedWriter bw = new BufferedWriter(fw);
            String cadena_leida;

            for(int i = 0; i<(datos_user.length - 1); i++)
                bw.write(datos_user[i]+",");
            bw.write(datos_user[4]);
            
            bw.close();
            fw.close();
            
        }catch(IOException e)
        {
            System.out.println("Excepcion de lectura/escritura detectada.");
        }
        
        for(int i = 0; i<datos_user.length; i++)
        {
            System.out.println("["+(i+1)+"]"+datos_user[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonHacerDeposito = new javax.swing.JButton();
        ButtonModDatos = new javax.swing.JButton();
        ButtonRetirarDinero = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelEdo = new javax.swing.JLabel();
        labelFondos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido, user.");

        ButtonHacerDeposito.setText("Hacer Deposito");
        ButtonHacerDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHacerDepositoActionPerformed(evt);
            }
        });

        ButtonModDatos.setText("Modificar Datos");
        ButtonModDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModDatosActionPerformed(evt);
            }
        });

        ButtonRetirarDinero.setText("Retirar Dinero");
        ButtonRetirarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetirarDineroActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos:"));

        labelNombre.setText("Nombre: nombre");

        labelApellido.setText("Apellido: apellido");

        labelFecha.setText("Fecha de Nacimiento: fecha ");

        labelEdo.setText("Estado natal: estado");

        labelFondos.setText("Fondos: fondos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelApellido)
                    .addComponent(labelFecha)
                    .addComponent(labelEdo)
                    .addComponent(labelFondos))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFondos)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonHacerDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonRetirarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonModDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModDatos)
                    .addComponent(ButtonHacerDeposito)
                    .addComponent(ButtonRetirarDinero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonHacerDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHacerDepositoActionPerformed
        // TODO add your handling code here:
        try{
            double fondos = Double.parseDouble(datos_user[4]);
            double retiro= Double.parseDouble(JOptionPane.showInputDialog("¿Cuanto quieres depositar?"));
            datos_user[4] = String.valueOf(fondos+retiro);
            labelFondos.setText("Fondos: "+datos_user[4]);
        }catch(NullPointerException e)
        {
            System.out.println(e.getMessage());
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Formato incorrecto. Ingresa solo numeros!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
        writeData();
    }//GEN-LAST:event_ButtonHacerDepositoActionPerformed

    private void ButtonRetirarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetirarDineroActionPerformed
        // TODO add your handling code here:
        try{
            double fondos = Double.parseDouble(datos_user[4]);
            double retiro= Double.parseDouble(JOptionPane.showInputDialog("¿Cuanto quieres retirar?"));
            datos_user[4] = String.valueOf(fondos-retiro);
            labelFondos.setText("Fondos: "+datos_user[4]);
        }catch(NullPointerException e)
        {
            System.out.println(e.getMessage());
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Formato incorrecto. Ingresa solo numeros!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
        writeData();
    }//GEN-LAST:event_ButtonRetirarDineroActionPerformed

    private void ButtonModDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModDatosActionPerformed
        // TODO add your handling code here:
        appMod = new ModFrame(username);
        appMod.setVisible(true); //Abrimos la app principal
        this.dispose();
    }//GEN-LAST:event_ButtonModDatosActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHacerDeposito;
    private javax.swing.JButton ButtonModDatos;
    private javax.swing.JButton ButtonRetirarDinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelEdo;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFondos;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
